name: 'Linux Tests Host'
description: 'Linux test run in host OS'

runs:
  using: "composite"
  steps:
    - name: Setup JDK 26
      uses: actions/setup-java@v5
      with:
        distribution: 'corretto'
        java-version: '26'

    - name: Tests Host
      shell: bash
      run: |
        cat /etc/os-release
        java -version
        java                                                \
          -cp ./build/release/duckdb_jdbc_tests.jar:./build/release/duckdb_jdbc.jar \
          org.duckdb.TestDuckDBJDBC
